export const products= [
    { 
        img : "/product1.png",
        id:1,
        categoria:'Laptops',
        nombre:'Apple Mac Book Pro',
        precio: 950.00,
        descripcion:'Thanks to the new M2 chip, the 13-inch MacBook Pro is more powerful than ever. It offers up to 20 hours of battery life and an active cooling system that maintains performance.',
        coloresDisponibles:[ 'black','orange','gray'],
    },
    {
        img:"/product2.png",
        id:2,
        categoria:'Phones',
        nombre:'iPhone Pro 11',
        precio: 900.00,
        descripcion:'The iPhone 11 screen has rounded corners that finish off the phone curved design, and those corners sit within a standard rectangle.',
        coloresDisponibles:[ 'black','orange','gray'],
    },
    {
        img: "/product3.png",
        id:3,
        categoria:'TV',
        nombre:'Samsung Qled 4K',
        precio: 950.00,
        descripcion:'Bright, long-lasting color with Quantum Dot. One billion shades of color with Quantum Dot and a greater contrast range on a cinematic scale.',
        coloresDisponibles:[ 'black','orange','gray'],
    },
    {
        img :"/product4.png",
        id:4,
        categoria:'Phones',
        nombre:'Samsung Galaxy s10',
        precio: 950.00,
        descripcion:'Powering the Galaxy S10 is the Samsung Exynos 9820 SoC that is very capable and can run most apps and games on the app store. This powerful SoC is paired with 8GB of RAM and 128GB of storage which makes it very easy for multitasking with this smartphone.',
        coloresDisponibles:[ 'black','orange','gray'],
    },
    {
        img: "/product5.png",
        id:5,
        categoria: 'Tablets',
        nombre:'iPad Pro 11',
        precio: 450.00, 
        descripcion:'Outstanding performance, incredibly advanced displays, ultra-fast wireless, powerful new features with iPadOS 16, and a touch of magic for Apple Pencil. The iPad at its best.',
        coloresDisponibles:[ 'black','orange','gray'],
    },
    {
        img: "/product6.png",
        id:6,
        categoria:'Gadgets',
        nombre:'Google Nest',
        precio: 1000.00,
        descripcion:'Nest Audio adapts to your environment and what you`re listening to.',
        coloresDisponibles:[ 'black','orange','gray'],
    },
    {
        img: "/product7.png",
        id:7,
        categoria:'Tablets',
        nombre:'Microsoft Surface Studio',
        precio: 950.00,
        descripcion:'Unleash your imagination on Surface Laptop Studio. The barrier-breaking design lets you unleash your creativity on the sleek 14-inch 120Hz PixelSense™ Flow touchscreen.',
        coloresDisponibles:[ 'black','orange','gray'],
    },
    {
        img:"/product8.png",
        id:8,
        categoria:'Watches',
        nombre:'Samsung Watch',
        precio: 950.00,
        descripcion:'biometric control applications, such as Samsung Health, which allows you to track sleep patterns, heart rate, etc.',
        coloresDisponibles:[ 'black','orange','gray'],
    },
    {
        img:"/product9.png",
        id:9,
        categoria:'TV',
        nombre:'Pro Display XDR',
        precio: 1000.00,
        descripcion:'The worlds first 32-inch Retina 6K display. Up to 1,600 nits of brightness.',
        coloresDisponibles:[ 'black','orange','gray'],
    },
    {
        img:"/product10.png",
        id:10,
        categoria:'Black Friday',
        nombre: 'Gamepad Xbox One X',
        precio: 950.00,
        descripcion:'Enjoy the modernized design of the Xbox Wireless Controller, with sculpted surfaces and refined geometry for greater comfort during gameplay.',
        coloresDisponibles:[ 'black','orange','gray'],
    },
    {
        img:"/product11.png",
        id:11,
        categoria:'Watches',
        nombre:'Smart Watch',
        precio: 800.00,
        descripcion:'The strongest and most equipped Apple Watch pushes the limits once again. Now with the brand new S9 SiP, a magical new way to use your watch without even touching the screen, Apples brightest yet.',
        coloresDisponibles:[ 'black','orange','gray'],
    },
    {
        img:"/product12.png",
        id:12,
        categoria:'Gadget',
        nombre:'Google Nest',
        precio: 600.00,
        descripcion:'With Nest Audio woofers, tweeters and tuning software, your room will be filled with rich bass and clear vocals.',
        coloresDisponibles:[ 'black','orange','gray'],
    },
    {
        img:"/product13.png",
        id:13,
        categoria:'Laptops',
        nombre:'Galaxy Book3 Pro 360',
        precio: 3000.00,
        descripcion:'Immerse yourself in crisp, true-to-life 3K (2880 x 1800) resolution that lets you see everything in vivid color and sharp detail, even if your office is outdoors.',
        coloresDisponibles:[ 'black','orange','gray'],
    },
    {
        img:"/product14.png",
        id:14,
        categoria:'Gadgets',
        nombre:'Ipod',
        precio: 600.00,
        descripcion:'A lot more than just a way to play digital music.',
        coloresDisponibles:[ 'black','orange','gray'],
    },
    {
        img:"/product15.png",
        id:15,
        categoria:'Watches',
        nombre:'Apple Watch SE',
        precio:600.00,
        descripcion:'When you see everything the Apple Watch SE offers you, its price will be irresistible.',
        coloresDisponibles:[ 'black','orange','gray'],
    },
]
